config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :bus_operators, concerns: :paginatable do
    resources :reviews, only: :index, concerns: :paginatable
  end

  resources :reviews, only: :create

  root to: 'bus_operators#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus_operator.rb
class BusOperator < ApplicationRecord
  BUS_OPERATORS_UPDATE_URL = 'https://www.recorrido.cl/api/v2/es/bus_operators.json'
  MODEL_ATTRS = ['external_id', 'internal_name', 'official_name', 'bookable', 'phone', 'allows_e_ticketing', 'average_rating', 'payload']
  ORDER_ATTR = ['official_name', 'average_rating']
  include Sortable

  has_many :reviews

  after_create :create_initial_reviews

  def self.update
    response = RestClient.get(BUS_OPERATORS_UPDATE_URL)
    bus_operators = JSON.parse(response.body)['bus_operators']
    already_created_ids = BusOperator.where(external_id: bus_operators.map{|o| o['id']}).pluck(:external_id)
    to_be_created = bus_operators.reject {|o| already_created_ids.include?(o['id'].to_i)}
    to_be_created.each do |operator|
      operator = format_operator operator
      find_or_create operator
    end
  end

  # Menos óptimo :(
  # def self.update
  #   response = RestClient.get(BUS_OPERATORS_UPDATE_URL)
  #   bus_operators = JSON.parse(response.body)['bus_operators']
  #   operator_ids = bus_operators.each do |operator|
  #     operator = format_operator operator
  #     find_or_create operator
  #   end
  # end

  def rating_percentage
    average_rating.nil? ? 0 : average_rating * 100 / 5
  end

  private

  def create_initial_reviews
    return if average_rating.nil?
    10.times do
      review = self.reviews.build(rating: average_rating)
      review.save
    end
  end

  def self.find_or_create operator
    self.create_with(operator)
        .find_or_create_by(external_id: operator['external_id'])
  end

  def self.format_operator operator
    operator['payload'] = operator
    operator['external_id'] = operator.delete('id')
    operator.extract!(*MODEL_ATTRS)
  end
end

app/models/concerns/sortable.rb
module Sortable
  extend ActiveSupport::Concern

  included do
    scope :order_by_option, -> (attribute, opt) do
      case opt
      when :desc
        order("#{attribute} DESC")
      when :null_desc
        order("#{attribute} DESC NULLS LAST")
      else
        order(attribute)
      end
    end
  end

  # No se hace automaticamente
  # module ClassMethods
  #   def add_sortable_scopes
  #     scope :order_by_option, -> (attribute, opt) do
  #       case opt
  #       when :desc
  #         order("#{attribute} DESC")
  #       when :null_desc
  #         order("#{attribute} DESC NULLS LAST")
  #       else
  #         order(attribute)
  #       end
  #     end
  #   end
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  include Sortable

  belongs_to :bus_operator

  after_create :update_average_rating

  scope :bus_operator, -> (id) { where(bus_operator_id: id) }

  private

  def update_average_rating
    average = self.class.bus_operator(bus_operator_id).average(:rating)
    bus_operator.update(average_rating: average)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bus_operators_controller.rb
class BusOperatorsController < ApplicationController
  before_action :update_bus_operators, :set_bus_operator_order, only: :index
  before_action :set_bus_operator, only: [:show, :edit, :update]

  def index
    @bus_operators = BusOperator.order_by_option(
                                  @order_selected,
                                  order_options[@order_selected.to_sym])
                                .page(params[:page])
                                .per(20)
  end

  def show
    @review = @bus_operator.reviews.build
  end

  def edit
  end

  def update
    if @bus_operator.update(bus_operator_params)
      render :show
    else
      render :edit
    end
  end

  private
  def update_bus_operators
    BusOperator.update
  end

  def set_bus_operator
    @bus_operator = BusOperator.find(params[:id])
  end

  def bus_operator_params
    params.require(:bus_operator).permit(:description)
  end

  def set_bus_operator_order
    @order_selected = params[:bus_operator].try(:[], 'order_by') || 'id'
  end

  def order_options
    {
      official_name: :asc,
      average_rating: :null_desc,
      id: :asc
    }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_bus_operator
  def index
    @reviews = @bus_operator.reviews
                            .order_by_option('created_at', :desc)
                            .page(params[:page])
                            .per(20)
  end

  def create
    @review = @bus_operator.reviews.build(review_params)
    if @review.save
      redirect_to bus_operator_reviews_path(@bus_operator)
    else
      redirect_to bus_operator_path(@bus_operator)
    end
  end

  private

  def set_bus_operator
    @bus_operator = BusOperator.find(params[:bus_operator_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment, :bus_operator_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bus_operators/_review_form.html.erb
<%= bootstrap_form_with(model: review, url: reviews_url, local: true) do |f| %>
  <%= f.text_area :comment %>
  <fieldset class="rating form-control">
    <input type="radio" id="star5" name="review[rating]" value="5" /><label class = "full" for="star5"></label>
    <input type="radio" id="star4half" name="review[rating]" value="4.5" /><label class="half" for="star4half"></label>
    <input type="radio" id="star4" name="review[rating]" value="4" /><label class = "full" for="star4"></label>
    <input type="radio" id="star3half" name="review[rating]" value="3.5" /><label class="half" for="star3half"></label>
    <input type="radio" id="star3" name="review[rating]" value="3" /><label class = "full" for="star3"></label>
    <input type="radio" id="star2half" name="review[rating]" value="2.5" /><label class="half" for="star2half"></label>
    <input type="radio" id="star2" name="review[rating]" value="2" /><label class = "full" for="star2"></label>
    <input type="radio" id="star1half" name="review[rating]" value="1.5" /><label class="half" for="star1half"></label>
    <input type="radio" id="star1" name="review[rating]" value="1" /><label class = "full" for="star1"></label>
    <input type="radio" id="starhalf" name="review[rating]" value="0.5" /><label class="half" for="starhalf"></label>
  </fieldset>
  <%= hidden_field_tag :bus_operator_id, bus_operator.id  %>
  <%= f.submit t('.submit'), class: "btn btn-primary" %>
<% end %>

app/views/bus_operators/edit.html.erb
<div class="container">
  <div class="row">
    <h2>
      <%= t('.title', official_name: @bus_operator.official_name.titleize) %>
      <small>
        <%= link_to(@bus_operator) do %>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true" title="<%= t('.show', official_name: @bus_operator.official_name.titleize) %>"></span>
        <% end %>
      </small>
    </h2>
  </div>
  <div class="row">
    <%= bootstrap_form_with(model: @bus_operator, local: true) do |f| %>
      <%= f.text_area :description %>
      <%= f.submit t('.submit'), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bus_operators/index.html.erb
<div class="container">
  <div class="row">
    <h2><%= t('.title') %></h2>
  </div>
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4 form-group">
      <%= bootstrap_form_with(url: bus_operators_url, method: 'get', local: true, class: 'form-inline pull-right') do |f| %>
        <%= select('bus_operator', 'order_by', BusOperator::ORDER_ATTR.collect {|attr| [BusOperator.human_attribute_name(attr), attr] }, { include_blank: true, selected: @order_selected }, { class: 'form-control' }) %>
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped bus-operator-table">
        <thead>
        </thead>
        <tbody>
          <% @bus_operators.each do |operator| %>
          <tr>
            <td>
              <%= image_tag(operator.payload['icons']['thumb']) %>
            </td>
            <td>
              <%= operator.official_name %>
            </td>
            <td>
              <% if operator.average_rating.present? %>
                <div class="star-rating" title="<%= operator.rating_percentage %>%">
                  <div class="back-stars">
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <div class="front-stars" style="width: <%= operator.rating_percentage %>%">
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    </div>
                  </div>
                </div>
              <% end %>
            </td>
            <td>
              <%= link_to(edit_bus_operator_path(operator)) do %>
                <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="<%= t('.edit') %>"></span>
              <% end %>

              <%= link_to(operator) do %>
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true" title="<%= t('.show', official_name: operator.official_name.titleize) %>"></span>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <%= paginate @bus_operators, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered' %>
  </div>
</div>

app/views/bus_operators/show.html.erb
<div class="container">
  <div class="row">
    <h2>
      <%= t('.title', official_name: @bus_operator.official_name.titleize) %>
      <small>
        <%= link_to(edit_bus_operator_path(@bus_operator)) do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="<%= t('.edit') %>"></span>
        <% end %>
        <%= link_to(bus_operator_reviews_path(@bus_operator)) do %>
          <span class="glyphicon glyphicon-star" aria-hidden="true" title="<%= t('.reviews') %>"></span>
        <% end %>
      </small>
    </h2>
  </div>
  <div class="row">
    <div class="col-md-8">
      <label><%= BusOperator.human_attribute_name :average_rating %></label>
      <p><%= number_with_precision(@bus_operator.average_rating, precision: 2) %></p>
      <label><%= BusOperator.human_attribute_name :description %></label>
      <p><%= @bus_operator.description %></p>

      <%= render partial: 'review_form', locals:
        { review: @review, bus_operator: @bus_operator }
      %>
    </div>
    <div class="col-md-4">
      <%= image_tag(@bus_operator.payload['images']['hdpi']) %>
    </div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusOperatorsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body class="fixed skin-blue-light">
    <div class="wrapper">
      <%= render 'layouts/navigation/layout'%>
      <div class="content-wrapper">
        <div class="jumbotron">
          <%= yield %>
        </div>
      </div>
      <%= render 'layouts/navigation/footer'%>
    </div>
  </body>
</html>

app/views/layouts/navigation/_header.erb
<div class="navbar navbar-default">
  <div class="container-fluid">
    <nav class="navbar navbar-light">
      <a class="navbar-brand" href="/">Operadores de Buses</a>
    </nav>
  </div>
</div>

app/views/layouts/navigation/_layout.erb
<%= render "layouts/navigation/header" %>
<%= render "layouts/navigation/sidebar" %>

app/views/reviews/index.html.erb
<div class="container">
  <div class="row">
    <h2>
      <%= t('.title', official_name: @bus_operator.official_name.titleize) %>
      <small>
        <%= link_to(@bus_operator) do %>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true" title="<%= t('.show', official_name: @bus_operator.official_name.titleize) %>"></span>
        <% end %>
      </small>
    </h2>
  </div>
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t('.rating') %></th>
          <th><%= t('.comment') %></th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td>
              <%= review.rating %>
            </td>
            <td>
              <%= review.comment %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <%= paginate @reviews, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered' %>
  </div>
</div>